   
 INSERT INTO  
XXBCM_INVOICES (
INVOICE_REF,
INVOICE_DATE, 
INVOICE_STATUS, 
INVOICE_HOLD_REASON,
INVOICE_DESCRIPTION,
INVOICE_AMOUNT,
ORDER_REF,
SUPPLY_REF
)
    SELECT 
INVOICE_REFERENCE,
TO_DATE(INVOICE_DATE,'DD/MM/YYYY'),  
INVOICE_STATUS, 
INVOICE_HOLD_REASON,
INVOICE_DESCRIPTION,
TO_NUMBER(REPLACE(INVOICE_AMOUNT, ',', '')),
ORDER_REF,
SUPPLIER_NAME
               
FROM XXBCM_ORDER_MGT;