INSERT INTO  
XXBCM_ORDERS (
ORDER_REF,
ORDER_DATE, 
ORDER_TOTAL_AMOUNT, 
ORDER_STATUS,
ORDER_LINE_AMOUNT,
ORDER_DESCRIPTION,
SUPPLY_REF
)
    SELECT 
 ORDER_REF,
TO_DATE(ORDER_DATE,'DD/MM/YYYY'), 
TO_NUMBER(REPLACE(ORDER_TOTAL_AMOUNT, ',', '')),
ORDER_STATUS,
SUPPLIER_NAME
               
FROM XXBCM_ORDER_MGT;