INSERT INTO  
XXBCM_SUPPLIERS (
SUPPLIER_NAME,
SUPP_CONTACT_NAME, 
SUPP_ADDRESS, 
SUPP_CONTACT_NUMBER, 
SUPP_EMAIL
)
    SELECT DISTINCT SUPPLIER_NAME,
    SUPP_CONTACT_NAME,
           SUPP_ADDRESS,
           SUPP_CONTACT_NUMBER,
           SUPP_EMAIL
         
                      
FROM XXBCM_ORDER_MGT;