--------------------------------------------------------
--  File created - Sunday-December-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXBCM_ORDERS
--------------------------------------------------------

  CREATE TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" 
   (	"ORDER_REF" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDER_DATE" DATE, 
	"ORDER_TOTAL_AMOUNT" NUMBER, 
	"ORDER_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLY_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBCM_ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBCM_ORDER_MGT"."XXBCM_ORDERS_PK" ON "XXBCM_ORDER_MGT"."XXBCM_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table XXBCM_ORDERS
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" MODIFY ("SUPPLY_REF" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" MODIFY ("ORDER_REF" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" ADD CONSTRAINT "XXBCM_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table XXBCM_ORDERS
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDERS" ADD CONSTRAINT "XXBCM_ORDERS_FK1" FOREIGN KEY ("SUPPLY_REF")
	  REFERENCES "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ("SUPPLIER_NAME") ENABLE;
