--------------------------------------------------------
--  File created - Sunday-December-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXBCM_SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" 
   (	"SUPPLIER_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPP_CONTACT_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPP_ADDRESS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPP_CONTACT_NUMBER" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPP_EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUPPLIER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBCM_SUPPLIERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS_UK1" ON "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ("SUPPLIER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBCM_SUPPLIERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS_PK" ON "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table XXBCM_SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ADD CONSTRAINT "XXBCM_SUPPLIERS_UK1" UNIQUE ("SUPPLIER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ADD CONSTRAINT "XXBCM_SUPPLIERS_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS_PK"  ENABLE;
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPPLIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPP_CONTACT_NAME" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPP_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPP_CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" MODIFY ("SUPP_EMAIL" NOT NULL ENABLE);
