--------------------------------------------------------
--  File created - Sunday-December-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXBCM_ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDER_DETAILS" 
   (	"ORDER_DETAIL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_DESCRIPTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDER_REF" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDER_LINE_AMOUNT" NUMBER(10,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBCM_ORDER_MGT"."ORDER_DETAILS_PK" ON "XXBCM_ORDER_MGT"."XXBCM_ORDER_DETAILS" ("ORDER_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table XXBCM_ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDER_DETAILS" MODIFY ("ORDER_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDER_DETAILS" MODIFY ("ORDER_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_PK" PRIMARY KEY ("ORDER_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
