--------------------------------------------------------
--  File created - Sunday-December-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXBCM_INVOICES
--------------------------------------------------------

  CREATE TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" 
   (	"INVOICE_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_DATE" DATE, 
	"INVOICE_STATUS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_HOLD_REASON" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_DESCRIPTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_AMOUNT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ORDER_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUPPLY_REF" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBCM_INVOICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBCM_ORDER_MGT"."XXBCM_INVOICES_PK" ON "XXBCM_ORDER_MGT"."XXBCM_INVOICES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table XXBCM_INVOICES
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" MODIFY ("SUPPLY_REF" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" MODIFY ("ORDER_REF" NOT NULL ENABLE);
  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" ADD CONSTRAINT "XXBCM_INVOICES_PK" PRIMARY KEY ("INVOICE_ID")
  USING INDEX "XXBCM_ORDER_MGT"."XXBCM_INVOICES_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table XXBCM_INVOICES
--------------------------------------------------------

  ALTER TABLE "XXBCM_ORDER_MGT"."XXBCM_INVOICES" ADD CONSTRAINT "XXBCM_INVOICES_FK2" FOREIGN KEY ("SUPPLY_REF")
	  REFERENCES "XXBCM_ORDER_MGT"."XXBCM_SUPPLIERS" ("SUPPLIER_NAME") ON DELETE SET NULL ENABLE;
